import type { Metadata } from "next";
import { Geist, Geist_Mono, Baloo_Tamma_2 } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/LanguageContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const baloo = Baloo_Tamma_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // scegli quelli che ti servono
  variable: "--font-baloo",
});

export const metadata: Metadata = {
  title: "EctoSweets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html
  lang="en"
  className={`${geistSans.variable} ${geistMono.variable} ${baloo.variable} h-full antialiased`}
>
      <body className={`${baloo.className} min-h-full flex flex-col`}>n
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
